title: Portofolio
description: A portofolio of Raden Harya Dananjaya
sitename: Raden Harya Dananjaya
baseurl: '/portofolio'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
